### ISSUE TITLE
Que mapa de top 7 anfitriones coincida con lista

### ISSUE THREAD

**Issue by numeroteca** [montera34/airbnb.efecto#3]
Avisar a Xabier Orekari.

**Comment by numeroteca** [comment]
Revisar los datos de Patricia: aparecen 3 y cada una con datos diferentes.
La base de datos cuenta con 2 patricias, pero no con tres.

**Comment by numeroteca** [comment]
Corregida lista de top 7 junto al mapa 14727bd
Falta cambiar el mapa para que muestre los top 7 con más plazas y no los top7 con más alojamientos.
@xabiORK Puedes cambiar el mapa, o mejor, generar uno nuevo con los top 7 con más plazas?

**Comment by xabiORK** [comment]
Sí me encargo!

**Comment by xabiORK** [comment]
Hecho! ya está actualizado.
Me dado cuenta de una errata en la leyenda con la imagen de los anfitriones. En Francisco las viviendas y las plazas estan al revés.
Por otro lado veo los planos que están en formato imagen plana, algo deformados... da un poco al ojo. @numeroteca @skotperez

**Comment by numeroteca** [comment]
- [x] Corregida la errata de Francisco.
- [x] Los planos deformados creo que tienen que ver con la proyección (mercator u otras). Salían así por defecto de QGis y no los he modificado. Se podrían cambiar facilmente.

Gracias!
